CREATE TRIGGER tr_CascadeDeleteUser ON Users
INSTEAD OF DELETE
AS
BEGIN

	DELETE FROM UsersChats WHERE UserId = (SELECT Id FROM deleted)
	DELETE FROM Messages WHERE UserId = (SELECT Id FROM deleted)
	DELETE FROM Users WHERE Id = (SELECT Id FROM deleted)

END

-- ON SINGLE DELETE
BEGIN TRAN
DELETE FROM Users WHERE Users.Id = 1
ROLLBACK

-- ON MULTIPLE DELETE
BEGIN TRAN
DELETE FROM Users WHERE Users.Id IN (1, 2, 3)
ROLLBACK